name = "MNPDynamics"
uuid = "f81e04c9-20b8-526d-9626-780ee78293fb"
authors = ["Tobias Knopp <tobias@knoppweb.de>, Hannes Albers, Tobias Kluth, Marco Maass, Martin MÃ¶ddel"]
version = "0.1.1"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Aqua = "0.8"
Distributed = "1"
FLoops = "0.2"
HDF5 = "0.16, 0.17"
ImageFiltering = "0.7"
Interpolations = "0.14, 0.15, 0.16"
LinearAlgebra = "1"
LinearSolve = "1.23, 2, 3"
OffsetArrays = "1"
OrdinaryDiffEq = "6"
ProgressMeter = "1.9"
Random = "1"
SharedArrays = "1"
SparseArrays = "1"
SparseDiffTools = "2"
SpecialFunctions = "2.3"
StaticArrays = "1.9"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
